# Generated by Django 4.0.5 on 2022-09-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-03-05'),
            preserve_default=False,
        ),
    ]
