# Generated by Django 4.0.5 on 2022-09-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='fghj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
